apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-implantacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
        - name: web
          image: nginx:latest
        - name: banco-de-dados
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: curso
            - name: MYSQL_USER
              value: ajwfl
