apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment 
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ajwfl/sampletodo:latest
          ports:
            - containerPort: 8080
          env:
#           - name: DATABASE_URL
#             value: jdbc:mysql://db:3306/curso
            - name: "MYSQL_ROOT_PASSWORD"
              value: "root"
            - name: "MYSQL_DATABASE"
              value: "curso"
            - name: "MYSQL_USER"
              value: "root"